### ISSUE TITLE
Monitor and address N8N performance issues

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#12264]
Maikel has been working on caching proxy, we haven't seen it in Production so not quite sure. Issue might be when the cache expires that there would be a lot of requests to n8n

Possibly stagger cache times?
Quite tricky to work with it
Downtimes can be about 5 minutes when it does go down
When it goes down, anything triggered by webhooks it will know and will try again. We are not sure what would happen if there's a timing request. Not serious enough yet to spend time coming up with auto-solution 

Setting up new N8N server
- [x] spin up a server,
- [x] install n8n,
- [x] import a backup file
- [x] deactivate all active to start with
- [x] migrate user with there associated workflow and credentials
- [x] include the server in our SPF record so that it can send emails
- [x] set up email setting so it can send emails (work for N8N instance, but not from workflow)
- [x] set up automatic backups again
- [x] ~~tweak the n8n config a little bit to control number of processes and threads.,~~ or move `queue` mode : https://docs.n8n.io/hosting/scaling/queue-mode/ (We can add remove worker if needed and play with work conrency)
- [x] document and test recovery process

**Comment by kirstenalarsen** [comment]
@mkllnk is meeting with @RaggedStaff  on Friday morning to discuss upgrade and what it might break . . 
There is some concern about lots of workflows that don't have error tracking etc . .

**Comment by rioug** [comment]
Set up new N8N server
- [ ] spin up a server,
- [ ] install n8n,
- [ ] import a backup file
- [ ] deactivate all active to start with
- [ ] include the server in our SPF record so that it can send emails
- [ ] set up automatic backups again
- [ ] tweak the n8n config a little bit to control number of processes and threads.

**Comment by rioug** [comment]
Server is up and running at : https://n8n.openfoodnetwork.org/ , you can find the credentials in Bitwarden

I added Maikel's and David's key so they should be able to access it via ssh.

All workflow have been imported and are all disabled We are now on version 1.32.2 so some workflow might be broken. I have not tested anything.

See above for what is yet to be done. 

> tweak the n8n config a little bit to control number of processes and threads.

@mkllnk  I am not sure what you mean by this, I can't find anything related to that in N8N docs, regarding scaling there is page : https://docs.n8n.io/hosting/scaling/queue-mode/

>  set up automatic backups again 

I'll need to look into setting up some script, as currently backup are handled by Cloudron, but we should be able to set up something using AWS CLI and cron 

> set up email setting so it can send emails

We need to : as Google admin, you need to go to Gmail -> Routing and add the IP address as allowed sender.
And then finish configuring N8N, see the `.env` file on the server

**Comment by mkllnk** [comment]
Credentials have not been copied.

**Comment by mkllnk** [comment]
And we still can't use SSL. Same error as on the old one. Maybe we need to contact n8n support?

> SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354

**Comment by mkllnk** [comment]
> tweak the n8n config a little bit to control number of processes and threads.

I was just relaying what Garethe told me. But looking at the docs you linked, this could be possible with queue mode and workers which use concurrency: https://docs.n8n.io/hosting/scaling/queue-mode/#configure-worker-concurrency

The default is 10 already, actually. So one or two workers could be enough. I'm not sure if we also need to add additional webhook processes.

**Comment by rioug** [comment]
Running in `queue` mode isn't recommended with SQLite see: https://docs.n8n.io/hosting/scaling/queue-mode/#set-executions-mode. I would need to set up redis and Postgres.

I'll keep it set up with SQLite for now, we an explore a more scalable setup if we need to.

**Comment by rioug** [comment]
> And we still can't use SSL. Same error as on the old one. Maybe we need to contact n8n support?

    SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354


This should work now, I updated n8n config as suggested here https://community.n8n.io/t/smtp-ssl-error/1916/17 , you might need to turn SSL/TLS on google side though.

**Comment by rioug** [comment]
> Credentials have not been copied.
@mkllnk I imported all the credentials, you might want to check if you have duplicate credential from Discovery Regen

**Comment by mkllnk** [comment]
> I imported all the credentials,

That didn't work. The credentials are there but they can't be decrypted. I guess that the new instance generated its own encryption key.

**Comment by mkllnk** [comment]
SMTP via TLS still doesn't work.

The suggestion in the mentioned script was to turn TLS (port 587) off so that STARTTLS (port 465) kicks in. Google requires TLS for all authenticated connections though. They don't seem to support STARTTLS.

My experiments:

- SSL on, port 587: SSL error
- SSL on, port 465: invalid login reported by Google
- SSL off, port 465: Unexpected socket close
- SSL off, port 25, no login: works a few times and then Google blocks it

**Comment by rioug** [comment]
FYI , The n8n instance is configured with SSL off, port 587 and require ssl/tls on the google routing entry

**Comment by mkllnk** [comment]
Okay, now I tried with SSL off and port 587: Server terminates connection. response=421-4.7.0

**Comment by rioug** [comment]
> > I imported all the credentials,
> 
> That didn't work. The credentials are there but they can't be decrypted. I guess that the new instance generated its own encryption key.

I copied across the encryption key, so now credential are working. 
However that doesn't fix the problem of importing user with their linked workflow and credentials. There is no official way to do that : https://community.n8n.io/t/how-to-migrate-users-with-workflows-and-credentials-links/25532

One solution would be to dump the table we need from the current postgres database and load it in the new SQLite database. 
Before I embark on this task, I think it would be good to check if the current set up would be enough performance wise for the discovery regen.

If we have to move to a more scalable setup with a postgres database, the migration should be easier. Hopefully we could just dump the database and reload it, but again we are using different version of N8N so might not be that easy. 

What do you think ?

**Comment by mkllnk** [comment]
I'm sure that we will need the queue mode with multiple workers and threads. And therefore Postgres is recommended. I think that we should do it properly now, get a clone of the old database or as close as possible and then it will be much easier to migrate the workflows including users and credentials.

Could you literally import the whole database?

**Comment by rioug** [comment]
> Could you literally import the whole database?

Maybe, but because we are on different version on N8N that might break, I'll have a look at the migration notes and give it a go. :crossed_fingers:

**Comment by rioug** [comment]
Quick update :
* I managed to set up N8N in queue mode
* I am still working on importing Users, Workflows and credentials. My initial try of importing the database failed, but there are some options I can explore.

I turned off N8N as it's currently not set up, an anyone who would load the page would have the ability to register as the new owner.

**Comment by rioug** [comment]
The server is up and running with User, Workflow and credentials copied from the old server. Super user credentials are the same as the old server.

**Comment by rioug** [comment]
@mkllnk  I managed to send an email from a workflow, using the "Send Email" node. 
I updated the credential "Google SMTP relay (no auth)" with port 587, and SSL/TLS off, so your workflow should be working now.

We'll need to keep an eye on it though, it seems to be a bit temperamental. If you test right after updating the node or crendential you'll get this error :  
`Server terminates connection. response=421-4.7.0 Try again later, closing connection.`
But If you wait a bit it works. I tested it with both my personal and work email.

**Comment by rioug** [comment]
I added New Relic to the server, so we can keep an eye on it.

Email is still an issue it's a bit intermittent. It was not working when I tried this afternoon, but somehow after restarting the containers it's fine again :shrug:

**Comment by rioug** [comment]
Looking at this https://support.google.com/a/answer/81126?hl=en. I think we should update the DNS record to include the IPv6 address, hopefully that will help.

**Comment by rioug** [comment]
* Emails are fixed, and I added documentation on what needs to be done to set it up 
* enabled `node-fetch` 
* added new relic for monitoring purposes
* currently running with 5 worker with concurrency set to 20

All files and documentation are here https://github.com/openfoodfoundation/n8n-install/ (Private repository for now)

TODO: 
* fix server configuration to allow n8n to connect to the database : https://github.com/openfoodfoundation/ofn-install/pull/925
* add down time alert in New Relic

**Comment by mkllnk** [comment]
node-fetch is working beautifully. Generally extremely happy with the new server.

@rioug, I noticed that tags got lost. Do you think we could restore them now without overriding the database?

**Comment by rioug** [comment]
I should be able to, the workflow were imported without changing id's so it's just a matter of copying data accross, with maybe a bit of massaging in between if the tags table has been updated.

I'll have a look.

**Comment by rioug** [comment]
I imported the tags, there were a couple of errors but the majority of workflow should now have the proper tag.

**Comment by mkllnk** [comment]
That's great, thank you!
