### ISSUE TITLE
Creating a new enterprise, can't select any state

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#218]
In the form for new enterprises the states are not loaded as long as no country was submitted. This is the case when first creating an enterprise. The drop-down field of states is just empty.

**Comment by pmackay** [comment]
This is resolved on UK. Will assume OK elsewhere but please reopen if an issue.

**Comment by lin-d-hop** [comment]
So on the UK servers I updated application.yml 
DEFAULT_COUNTRY_CODE: GB
rather than using DEFAULT_COUNTRY: 44 which is an ID and changes on different DBs. This meant that the states started loading correctly.

I do think there is still an issue here as if you change the country from the default on setting up the enterprise the states don't load. Super minor issue but may become more relevant when instances span a number of countries.

**Comment by lin-d-hop** [comment]
Putting this in Icebox. UK will never need to fix this but potentially a language (rather than country borders) instance will need to take a look.

**Comment by myriamboure** [comment]
Hi there, I have a related issue in France, as you guessed well :-)
The default country when an enterprise get registered is "Afghanistan"... to change that, should I go in the application.yml and make the same change as you did @lin-d-hop, DEFAULT_COUNTRY_CODE: FR ?
Also as you guessed, the states don't charge until we have chosen a country, but I don't see how to do differently, as we have cases in France of producers based abroad, so we need to enable them to choose another country than France... Can we just not require any state for other countries than France?
![screenshot from 2016-10-10 13-23-33](https://cloud.githubusercontent.com/assets/8135376/19234707/a6795a30-8eed-11e6-8222-4de65b3e4661.png)

**Comment by sauloperez** [comment]
AFAIK this is not a problem. I'm able to register an enterprise by picking a country and then selecting a state. Can we close this?

**Comment by myriamboure** [comment]
Yes I don't see any bug here, some way to improve the UX of course but let's close this and reopen when we want to address improving registration UX.
