### ISSUE TITLE
[Performance] UK Server is a temperamental beast

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4210]
## Description

This is possibly the most vague issue ever created....

UK server is temperamental. I find that in the mornings I can load pages about 3 times faster than in the afternoon. Some days we have multiple user complaints. Other days everything seems fine. 

I have no pattern to this. I have no explanation. All I have is frustration. And that is useful to no one.

## Expected Behavior

Pages load before the user's hair goes grey.

## Actual Behavior

Chaos.

## Steps to Reproduce

1. Ummmmmmm
2.
3.
4. :Shrugs:

## Context

We know we have a lot of performance issues.... but mostly they are consistent. This smells like there is something else going on on the server.

## Severity

I'm going to make an S3 for now.... but hoepfully a DevOps person will upgrade it :prayer:

## Your Environment

* Version used: v2.3.1 UK
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by sauloperez** [comment]
> I find that in the mornings I can load pages about 3 times faster than in the afternoon. Some days we have multiple user complaints.

We can start to correlate that with the available metrics. Could share dates when these happened?

**Comment by lin-d-hop** [comment]
Will from now. 
Reported 3:34pm 02/09

**Comment by lin-d-hop** [comment]
20:23 03/09
The following pages have taken 40+ seconds to load.
/Enterprises 
/Order_Cycles

**Comment by lin-d-hop** [comment]
11:75 04/09
The site is also still regularly timing out when loading too (reports, order cycles).

**Comment by lin-d-hop** [comment]
12:47 04/09
 It’s just taken me 1hr to fill in one order and it was an incredibly painful process.

**Comment by lin-d-hop** [comment]
12:17 04/09
Also the system is very slow atm and my shop front won't even open at the moment

**Comment by sauloperez** [comment]
I've been taking a look and these is what I found out from the screenshot below:



* The busiest hours are from 10h to 19h
* within that time window
  * `Spree::Api::ProductsController#bulk_products` is our worst ofender. Good news is that v2.4.0 includes a fix and we should see it go down the list
  * `ShopsController#index` follows very closely and it impacts even more users (not only admins).

**Comment by luisramos0** [comment]
hey @sauloperez nice analysis and really nice perf data in datadog btw 👏 

point i is fixed and to be released.
point iv is very well known, we need pagination on the product list.
and then point iii and iv are the same page, the shop list, we dont have a performance issue to improve this one, do we?

In the graph I see orders_and_fulfilment report with p90 at 46seconds.... I think this one is at the top of the perf backlog.

So, in a quick analysis, looks like there's nothing new here, we just need to crack on with the performance epic 💪

**Comment by kirstenalarsen** [comment]
I think we have lots of performance issues for shop page don't we? They're in backlog rather than dev ready - #3853 #3860 #4040 #4042 #4041 - I of course don't know what any of those mean :) But I would like them all done . . remember our metic of loading 10,000 products in under a minute . .

**Comment by luisramos0** [comment]
I wonder if we are on the same page Kirsten, point iv is about the "shop page" that you mention.

point ii and iii (I edited my post above to have correct points :-)) are about the "shop list page" - this is the one I am not sure we have an issue for.

**Comment by lin-d-hop** [comment]
9:11am to 10:10am 05/09
Yep shop still won’t load since I sent the email below do looks like there is a major issue

**Comment by lin-d-hop** [comment]
Sorry team. Shopfronts are now not loading on UK productions. This is an S1 now.

**Comment by lin-d-hop** [comment]
![CPU usage (%)](https://user-images.githubusercontent.com/8669848/64329633-7d59f600-cfc7-11e9-978d-7fc89c9620ec.png)

There is a CPU spike every hour on the hour. You can see it clearly at night. In the day there is other load and I think this job does not finish. We need to around this job asap please!

**Comment by lin-d-hop** [comment]
Unless anyone says otherwise, I'm going to monitor this over the coming days and see what we find. 
Fingers crossed we can close this one :crossed_fingers:
