### ISSUE TITLE
Shipping info on checkout screen on desktop does not span width of box and radio buttons are not acting as bullet points for the copy

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#6139]
Off the back of the mobile shopping UX work, where the edit cart and checkout screens had minimal changes made in this round, this is a small fix that will be super helpful when you have a large amount of content in the shipping info section (for an example of this look at the [AU Prom Coast Food Collective shipping info](https://openfoodnetwork.org.au/prom-coast-food-co-op/shop#/shop), they have order cycles open wed-mon)

## Expected Behavior
When going through checkout on a desktop device, the shipping options span the width of the shipping info section and if the copy does break onto multiple lines the copy on that second line is aligned with the top line of text (ie the radio button is like a bullet point)

## Actual Behaviour
The shipping options only span half the width, and the copy is aligned with the radio button (ie the radio button isn't like a bullet point) when there are multiple lines.

## Animated Gif/Screenshot
![shipping methods layout crap](https://user-images.githubusercontent.com/10949052/95154785-5bd8c880-07de-11eb-84f1-d9eb2b840d01.png)

## Workaround
n/a

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: latest
* Browser name and version: Chrome latest
* Operating System and version (desktop or mobile): desktop Mac Mojave

**Comment by lauriewayne** [comment]
Depending on how the shop has their shipping options named, this can be really confusing for a shop's customers. 

![Image 6-14-21 at 5 30 PM](https://user-images.githubusercontent.com/37803238/121969078-69106480-cd28-11eb-9813-9f6c71e6f07b.jpg)

**Comment by RachL** [comment]
@jaycmb I don't remember but I think the new checkout will fix this? Shall we move this one to the checkout split column so it gets tested?

**Comment by jaycmb** [comment]
It was not specifically addressed by @Erioldoesdesign but I assume it should be fixed by the new layout.
Yes, let´s move to handle alongside the checkout work.

**Comment by lauriewayne** [comment]
Thank you! This is helpful for communicating with the user (not making promises but it is confidence building to let them know we are definitely working on it).

**Comment by Erioldoesdesign** [comment]
It's definitely less visually confusing in the new checkout, but there can still be a long list of options if the hub/producer has added multiple!

New view:
<img width="394" alt="Screenshot 2021-06-15 at 19 45 33" src="https://user-images.githubusercontent.com/11681324/122106811-48bcd480-ce12-11eb-91fd-e4b1c7c69393.png">

**Comment by filipefurtad0** [comment]
This still occurs, if the shipping info and/or name string has no empty spaces in it:
![image](https://user-images.githubusercontent.com/49817236/152413940-9ca26a10-9edd-45e8-b420-29a3322c62f5.png)

Can also be visible on the shop front (left side below):
![Peek 2022-02-03 19-12](https://user-images.githubusercontent.com/49817236/152414087-4a4b5ab6-8fce-4c03-9369-84ab603f0b76.gif)

Reopening as S5.

**Comment by sigmundpetersen** [comment]
Should this still be fixed as part of the Split Checkout work?
Or should we rather remove it from the Epic?
