### ISSUE TITLE
Capybara timeout errors in Docker

### ISSUE THREAD

**Issue by jhsu802701** [openfoodfoundation/openfoodnetwork#6228]
When I run the tests in the Docker environment, I get long cascades of the following error:
```bash
        Capybara::ExpectationNotMet:
          Timed out waiting for Selenium session reset
        # /bundles/gems/capybara-2.18.0/lib/capybara/selenium/driver.rb:145:in `reset!'
        # ./spec/spec_helper.rb:122:in `block in restart_driver'
        # ./spec/spec_helper.rb:122:in `each'
        # ./spec/spec_helper.rb:122:in `restart_driver'
        # ./spec/spec_helper.rb:143:in `block (2 levels) in <top (required)>'
```

**Comment by Matt-Yorkley** [comment]
@jhsu802701 is this resolved now, after the recent merged changes?

**Comment by jhsu802701** [comment]
I'm still getting this Selenium timeout error.

**Comment by jhsu802701** [comment]
I tried increasing the Capybara.default_max_wait_time from 30 to 300 in order to avoid the timeout errors.  I got the error message "Error: PDF could not be generated!"  The culprit appears to be wkhtmltopdf.

**Comment by jhsu802701** [comment]
That said, I'm still getting thousands of Capybara timeout errors in addition to the PDF generation errors.
