### ISSUE TITLE
VAT not included in items on Stroudco shopfront

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#910]
This may be user error (in which case sorry for wasting your time!) but the products on the shopfront are displaying the price before VAT - see 2 screenshots attached.
Is there a setting somewhere that we need to change to make the shopfront price include VAT?
![screenshot 2016-04-15 18 17 28](https://cloud.githubusercontent.com/assets/10517702/14569503/0fbb9a1e-0337-11e6-91e5-616b14c55b14.png)
![screenshot 2016-04-15 18 17 44](https://cloud.githubusercontent.com/assets/10517702/14569504/0fc26d26-0337-11e6-8f1e-f517b91ad39e.png)

**Comment by lin-d-hop** [comment]
Looks as though this was a problem in the tax configuration at the instance level. Tax rate was _not_ set to 'included in price'.

I have now updated this so we're just waiting for the product cache to update to check it worked. I'm on a train with slow internet so struggling to do this properly right now, but it looks like updating tax settings does not trigger a cache update. This shouldn't really be an issue as tax settings should really be updated super rarely. Perhaps @RohanM might like to be aware of that though...

**Comment by NickWeir63** [comment]
Now it is not showing the VAT on either the shopfront or the order
![screenshot 2016-04-18 08 49 48](https://cloud.githubusercontent.com/assets/10517702/14597114/bbb4bf28-0542-11e6-9f64-9b4b400b91aa.png)

**Comment by lin-d-hop** [comment]
@NickWeir63 @oliver can you confirm the correct price of the tom long organic bitter please?
The tax setting have been updated and the tax appears included in the price now.

However if the price on the shopfront at £2.50 for the Tom Long bitter actually is the price without tax we have a bigger issue to fix here. If £2.50 on the shopfront is the correct price then this is fixed and everything has updated correctly.

**Comment by NickWeir63** [comment]
Thanks @lin-d-hop - but I think it is still not fixed.  The master price for a bottle of tom long is £1.92 (see first screenshot below), then we add a mark-up of 30% to Brewery products (see 2nd shot) and then the Brewery enterprsise fee is set to full rate VAT (3rd shot).  I tried changing the enterprise fee to inherit from product but the VAT is still not being added (Oliver I changed the enterprise fee back to 'full rate' in case this is how you want it).  The shopfront is showing the master price plus the 30% markup (£2.50) but not adding the 20% VAT which should take it to £3.00
![screenshot 2016-04-20 16 36 22](https://cloud.githubusercontent.com/assets/10517702/14681154/d5eea92c-0717-11e6-8bdc-739f5c6e86ed.png)
![screenshot 2016-04-20 16 38 39](https://cloud.githubusercontent.com/assets/10517702/14681155/d5f21c38-0717-11e6-9381-6ccbdb8722a6.png)
![screenshot 2016-04-20 16 39 47](https://cloud.githubusercontent.com/assets/10517702/14681157/d5f42cda-0717-11e6-898d-d88c43ab3413.png)

**Comment by lin-d-hop** [comment]
This has now been cleared up as a misunderstanding of how tax worked. Let me know if we need to open a new enhancement to make things work as @NickWeir63 and @Oliver expected.

More details:
http://community.openfoodnetwork.org/t/vat-included-excluded-from-price/361
